### ISSUE TITLE
leaving last 

### ISSUE THREAD

**Issue by divinebaibhav** [FlowForwarding/dynamiccharts#11]
Hi,
I have done this:
Yaxis on Right
X-axis on bottom;
I have following two issues:
a)To increase default zoom level and show scroll to last date on X-axis at right most. 
b) When i pass a list of dates on Xaxis.its leaving last one.that is. If i hve data from 1st May to 30th may.
Its shows 29th on extreme right.but may 30th is not visible.

In attached image: I have data till 5th May and graph is showing till 4rth May on xAxis.

![ios simulator screen shot 06-may-2015 3 34 04 pm](https://cloud.githubusercontent.com/assets/6783860/7491277/911b7756-f405-11e4-97c9-f591d64e4e9e.png)

thanks in advance
Baibhav Singh

**Comment by dostanko** [comment]
Hi, it's hard to say something without your data and code base.
Like a hack I can suggest to add one extra point a little bit in future with [NSNull null] value

**Comment by divinebaibhav** [comment]
Hi,
lot of thanks for reply.
I tried same thing but repeated the last record twice .so it was not working as it has same last date.
But [NSNull null] value get crashed.
At this:
"
 CGPoint pointP = [_graph pointByValueInGrid:@[points[0], val]];
            if ([val isKindOfClass:[NSNull class]] ){
                if (lastMoveInd != (ind -1) && [self fillSeries:i]){
                    [path addLineToPoint:CGPointMake( path.currentPoint.x, self.frame.size.height)];
                    [path moveToPoint: pointP];
                }
                lastMoveInd = ind;
            } 

Assertion failed: (CGFloatIsValid(x) && CGFloatIsValid(y)), function void CGPathMoveToPoint(CGMutablePathRef, const CGAffineTransform *, CGFloat, CGFloat), file Paths/CGPath.cc, line 254.

By the way its now showing last date which was  required....

:)
